spring:
  cloud:
    function:
      definition: kafkaConsumer;kafkaProducer
    stream:
      kafka:
        binder:
          replicationFactor: 1
          auto-create-topics: true
          brokers: ${KAFKA_BROKERS:localhost:9092}
      bindings:
        binding-out-0:
          content-type: text/plain
          group: great-erp
        kafkaConsumer-in-0:
          destination: sse-topic
          content-type: text/plain
          group: great-erp
        kafkaProducer-out-0:
          content-type: text/plain
          group: great-erp
