# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: great-erp
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ODlkOWUxYjhlNWJiYTc5MTU3NzI4NTBmYTRkYThkYTA5MDA4YWU3NjZmYTVmYWFjMWNlMDUyM2I2Zjc5YmE2MDQwNTgxYTAzYTEzZmNhMTFlMzI3OGExZmRiNGExZmNlMzE2NjM1NDJlMTI5NDFhODE3ODE5NWJhNzk4ZWY4ODA=
